FROM node:24
WORKDIR /app
COPY back/package*.json ./
RUN npm install
COPY back/ .

COPY back/entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh


EXPOSE 4000
EXPOSE 9229
CMD ["/app/entrypoint.sh"]
