services:
  frontend:
    build:
      context: .
      dockerfile: dockerfile.frontend
    depends_on:
      - backend
    ports:
      - "${FRONT_PORT}:3000"
    develop:
      watch:
        - action: sync
          path: ./front/src
          target: /app/src
          ignore:
            - .front/node_modules/
        - action: rebuild
          path: ./front/package.json

  backend:
    build:
      context: .
      dockerfile: dockerfile.backend
    develop:
      watch:
        - action: sync
          path: ./back/src
          target: /app/src
          ignore:
            - .back/node_modules/
        - action: sync
          path: ./back/__tests__
          target: /app/__tests__
        - action: sync
          path: ./back/prisma
          target: /app/prisma
        - action: rebuild
          path: ./back/package.json
        - action: rebuild
          path: ./back/entrypoint.sh
    ports:
      - "${BACK_PORT_MAIN}:4000"
      - "${BACK_PORT_SEC}:4001"
      - "${BACK_PORT_PRISMA}:5555"
      - "${BACK_PORT_DEBUG}:9229"
    environment:
      NODE_ENV: ${NODE_ENV}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    depends_on:
      - db

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  backend-logs: